spring:
  application:
    name: cremedia

  datasource:
    url: jdbc:mysql://localhost:3306/CreMedia
    username: root
    password: Password123#@!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: musayevcreate@gmail.com
    password: jrje qpay ympq eisn

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
application:
  security:
    jwt:
      secret-key: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkw"
      expiration: 86400000